site_name: SwitchTemplate
docs_dir: core/components/switchtemplate/docs/mkdocs
site_dir: _build/site
edit_uri: tree/master/core/components/switchtemplate/docs/mkdocs

repo_name: 'Jako/SwitchTemplate'
repo_url: https://github.com/Jako/SwitchTemplate

copyright: '&copy; 2014-2017 <a href="https://treehillstudio.com">Treehill Studio</a>'

pages:
- Description: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
- Donate: 'donate.md'

extra:
  font:
    text: 'Dosis'
    heading: 'Ubuntu'

piwik_analytics:
  site_id: 22
  piwik_url: 'https://piwik.partout.info/'

theme: 'material'
theme_dir: '/Users/jako/Documents/MODx/MkDocs Material/material'

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - meta
  - toc(permalink=true)
